const   rand = require('./random'),
        ca = require('./chaosAction'),
        async = require('async'),
        Nightmare = require('nightmare');

function createChaos(editorUrl) {

    let nightmare = Nightmare({
        show: false,
        waitTimeout: 600000, // 10 minutes
        typeInterval: 200
    });

    return nightmare
        .goto(editorUrl)
        .wait('input#username-input')
        .type('input#username-input', rand.randomChaosMonkey())
        .click('button#connect-btn')
        .wait(3000)
        .wait('ul#users-list div.user-name strong')        
        .wait(2000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())        
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000)
        .click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())        
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())        
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())        
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .wait(1000).click('div.ql-editor')
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())
        .type('div.ql-editor', ca.chaosAction())                
        .wait()
}

module.exports.run = () => {

    async.parallelLimit([
        function(callback) {
         createChaos()
         .end()
         .catch((err) =>{
             console.error(err);
             callback(err);
         })
        },
        function(callback) {
         createChaos()
         .end()
         .catch((err) =>{
             console.error(err);
             callback(err);
         })
        }
    ],
    2,
    function(err, results) {
        if (err) {
         console.error(`err: ${err}`);
        }
        console.log(`yeah: ${results}`);
    });

}